<?php
/**
 * Configuration constants file for error codes.
 * @author Irinel BUCUR
 */

define('_ERROR_ON_DATABASE_CONNECTION', 1);
define('_ERROR_ON_DECODING_THE_POST_JSON_INPUT', 2);
define('_ERROR_ON_DECODING_SINCE_METHOD_IS_NOT_POST', 3);
define('_ERROR_ON_DECODING_SINCE_POSTED_DATA_IS_NOT_APPLICATION_JSON', 4);

define('_ERROR_INVALID_LOGIN_DETAILS', 100);
define('_ERROR_INCOMPLETE_LOGIN_DETAILS_PASSED', 101);
define('_ERROR_USER_NOT_LOGGED_IN_TO_LOGOUT', 102);
define('_ERROR_USER_PASSWORD_CANNOT_BE_EMPTY', 103);
define('_ERROR_USER_PROFILE_DETAILS_ARE_INCOMPLETE', 104);
define('_ERROR_USER_EMAIL_IS_ALREADY_IN_USE', 105);
